/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  monitor_log: () => import("@/views/_builtin/monitor/log/index.vue"),
  monitor_online: () => import("@/views/_builtin/monitor/online/index.vue"),
  project_about: () => import("@/views/_builtin/project/about/index.vue"),
  setting_profile: () => import("@/views/_builtin/setting/profile/index.vue"),
  system_config: () => import("@/views/_builtin/system/config/index.vue"),
  system_dept: () => import("@/views/_builtin/system/dept/index.vue"),
  system_dict: () => import("@/views/_builtin/system/dict/index.vue"),
  system_dict_item: () => import("@/views/_builtin/system/dict/item/index.vue"),
  system_file: () => import("@/views/_builtin/system/file/index.vue"),
  system_menu: () => import("@/views/_builtin/system/menu/index.vue"),
  system_notice: () => import("@/views/_builtin/system/notice/index.vue"),
  system_role: () => import("@/views/_builtin/system/role/index.vue"),
  system_storage: () => import("@/views/_builtin/system/storage/index.vue"),
  system_user: () => import("@/views/_builtin/system/user/index.vue"),
  tool_generator: () => import("@/views/_builtin/tool/generator/index.vue"),
  home: () => import("@/views/home/index.vue"),
};
