/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  monitor_log: () => import("@/views/_builtin/monitor/log/index.vue"),
  monitor_online: () => import("@/views/_builtin/monitor/online/index.vue"),
  project_about: () => import("@/views/_builtin/project/about/index.vue"),
  system_config: () => import("@/views/_builtin/system/config/index.vue"),
  system_dept: () => import("@/views/_builtin/system/dept/index.vue"),
  system_dict: () => import("@/views/_builtin/system/dict/index.vue"),
  system_dict_item: () => import("@/views/_builtin/system/dict/item/index.vue"),
  system_file: () => import("@/views/_builtin/system/file/index.vue"),
  system_menu: () => import("@/views/_builtin/system/menu/index.vue"),
  system_notice: () => import("@/views/_builtin/system/notice/index.vue"),
  system_role: () => import("@/views/_builtin/system/role/index.vue"),
  system_storage: () => import("@/views/_builtin/system/storage/index.vue"),
  system_user: () => import("@/views/_builtin/system/user/index.vue"),
  tool_generator: () => import("@/views/_builtin/tool/generator/index.vue"),
  "user-center": () => import("@/views/_builtin/user-center/index.vue"),
  "function_hide-child_one": () => import("@/views/function/hide-child/one/index.vue"),
  "function_hide-child_three": () => import("@/views/function/hide-child/three/index.vue"),
  "function_hide-child_two": () => import("@/views/function/hide-child/two/index.vue"),
  "function_multi-tab": () => import("@/views/function/multi-tab/index.vue"),
  function_request: () => import("@/views/function/request/index.vue"),
  "function_super-page": () => import("@/views/function/super-page/index.vue"),
  function_tab: () => import("@/views/function/tab/index.vue"),
  "function_toggle-auth": () => import("@/views/function/toggle-auth/index.vue"),
  home: () => import("@/views/home/index.vue"),
  manage_dictionary: () => import("@/views/manage/dictionary/index.vue"),
  manage_menu: () => import("@/views/manage/menu/index.vue"),
  manage_role: () => import("@/views/manage/role/index.vue"),
  "manage_user-detail": () => import("@/views/manage/user-detail/[id].vue"),
  manage_user: () => import("@/views/manage/user/index.vue"),
  "multi-menu_first_child": () => import("@/views/multi-menu/first_child/index.vue"),
  "multi-menu_second_child_home": () => import("@/views/multi-menu/second_child_home/index.vue"),
  plugin_barcode: () => import("@/views/plugin/barcode/index.vue"),
  plugin_cascader: () => import("@/views/plugin/cascader/index.vue"),
  plugin_charts_echarts: () => import("@/views/plugin/charts/echarts/index.vue"),
  plugin_copy: () => import("@/views/plugin/copy/index.vue"),
  plugin_drag: () => import("@/views/plugin/drag/index.vue"),
  plugin_editor_markdown: () => import("@/views/plugin/editor/markdown/index.vue"),
  plugin_editor_md: () => import("@/views/plugin/editor/md/index.vue"),
  plugin_editor_quill: () => import("@/views/plugin/editor/quill/index.vue"),
  plugin_excel: () => import("@/views/plugin/excel/index.vue"),
  plugin_form_stepform: () => import("@/views/plugin/form/stepform/index.vue"),
  plugin_icon: () => import("@/views/plugin/icon/index.vue"),
  plugin_map: () => import("@/views/plugin/map/index.vue"),
  plugin_pinyin: () => import("@/views/plugin/pinyin/index.vue"),
  plugin_print: () => import("@/views/plugin/print/index.vue"),
  plugin_swiper: () => import("@/views/plugin/swiper/index.vue"),
  plugin_table_edittable: () => import("@/views/plugin/table/EditTable/index.vue"),
  plugin_video: () => import("@/views/plugin/video/index.vue"),
};
