/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.base$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.base$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.base$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about'
    }
  },
  {
    name: 'expired',
    path: '/expired',
    component: 'layout.base$view.expired',
    meta: {
      title: 'expired',
      i18nKey: 'route.expired'
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page'
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd)?',
    component: 'layout.base$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true
    }
  },
  {
    name: 'message',
    path: '/message',
    component: 'layout.base$view.message',
    meta: {
      title: 'message',
      i18nKey: 'route.message'
    }
  },
  {
    name: 'monitor',
    path: '/monitor',
    component: 'layout.base',
    meta: {
      title: 'monitor',
      i18nKey: 'route.monitor'
    },
    children: [
      {
        name: 'monitor_log',
        path: '/monitor/log',
        component: 'view.monitor_log',
        meta: {
          title: 'monitor_log',
          i18nKey: 'route.monitor_log'
        }
      },
      {
        name: 'monitor_online',
        path: '/monitor/online',
        component: 'view.monitor_online',
        meta: {
          title: 'monitor_online',
          i18nKey: 'route.monitor_online'
        }
      }
    ]
  },
  {
    name: 'profile',
    path: '/profile',
    component: 'layout.base$view.profile',
    meta: {
      title: 'profile',
      i18nKey: 'route.profile'
    }
  },
  {
    name: 'project',
    path: '/project',
    component: 'layout.base$view.project',
    meta: {
      title: 'project',
      i18nKey: 'route.project'
    }
  },
  {
    name: 'schedule',
    path: '/schedule',
    component: 'layout.base',
    meta: {
      title: 'schedule',
      i18nKey: 'route.schedule'
    },
    children: [
      {
        name: 'schedule_job',
        path: '/schedule/job',
        component: 'view.schedule_job',
        meta: {
          title: 'schedule_job',
          i18nKey: 'route.schedule_job'
        }
      },
      {
        name: 'schedule_log',
        path: '/schedule/log',
        component: 'view.schedule_log',
        meta: {
          title: 'schedule_log',
          i18nKey: 'route.schedule_log'
        }
      }
    ]
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system'
    },
    children: [
      {
        name: 'system_config',
        path: '/system/config',
        component: 'view.system_config',
        meta: {
          title: 'system_config',
          i18nKey: 'route.system_config'
        }
      },
      {
        name: 'system_dept',
        path: '/system/dept',
        component: 'view.system_dept',
        meta: {
          title: 'system_dept',
          i18nKey: 'route.system_dept'
        }
      },
      {
        name: 'system_dict',
        path: '/system/dict',
        meta: {
          title: 'system_dict',
          i18nKey: 'route.system_dict'
        },
        children: [
          {
            name: 'system_dict_item',
            path: '/system/dict/item',
            component: 'view.system_dict_item',
            meta: {
              title: 'system_dict_item',
              i18nKey: 'route.system_dict_item'
            }
          }
        ]
      },
      {
        name: 'system_file',
        path: '/system/file',
        component: 'view.system_file',
        meta: {
          title: 'system_file',
          i18nKey: 'route.system_file'
        }
      },
      {
        name: 'system_menu',
        path: '/system/menu',
        component: 'view.system_menu',
        meta: {
          title: 'system_menu',
          i18nKey: 'route.system_menu'
        }
      },
      {
        name: 'system_notice',
        path: '/system/notice',
        meta: {
          title: 'system_notice',
          i18nKey: 'route.system_notice'
        },
        children: [
          {
            name: 'system_notice_add',
            path: '/system/notice/add',
            component: 'view.system_notice_add',
            meta: {
              title: 'system_notice_add',
              i18nKey: 'route.system_notice_add'
            }
          },
          {
            name: 'system_notice_detail',
            path: '/system/notice/detail',
            component: 'view.system_notice_detail',
            meta: {
              title: 'system_notice_detail',
              i18nKey: 'route.system_notice_detail'
            }
          }
        ]
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: 'system_role',
          i18nKey: 'route.system_role'
        }
      },
      {
        name: 'system_storage',
        path: '/system/storage',
        component: 'view.system_storage',
        meta: {
          title: 'system_storage',
          i18nKey: 'route.system_storage'
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user'
        }
      }
    ]
  },
  {
    name: 'tool',
    path: '/tool',
    component: 'layout.base',
    meta: {
      title: 'tool',
      i18nKey: 'route.tool'
    },
    children: [
      {
        name: 'tool_generator',
        path: '/tool/generator',
        component: 'view.tool_generator',
        meta: {
          title: 'tool_generator',
          i18nKey: 'route.tool_generator'
        }
      }
    ]
  }
];
